// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGJSCykU4NpKXAlpyQDzW_uWccBFFzxRs',
    appId: '1:701387500306:web:1283280278a713d3ade1cb',
    messagingSenderId: '701387500306',
    projectId: 'flutter-chat-app-140f2',
    authDomain: 'flutter-chat-app-140f2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-140f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwtW4-q7FRIM4wzoKy_0hcOZwLDHvROfk',
    appId: '1:701387500306:android:67018e85c747af93ade1cb',
    messagingSenderId: '701387500306',
    projectId: 'flutter-chat-app-140f2',
    storageBucket: 'flutter-chat-app-140f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAds6KakydjRDucS7MaQeQjMtDz3wGlBTw',
    appId: '1:701387500306:ios:52bfafae5f6bcc7fade1cb',
    messagingSenderId: '701387500306',
    projectId: 'flutter-chat-app-140f2',
    storageBucket: 'flutter-chat-app-140f2.appspot.com',
    iosBundleId: 'com.chatapp.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAds6KakydjRDucS7MaQeQjMtDz3wGlBTw',
    appId: '1:701387500306:ios:49033a93b4dc7162ade1cb',
    messagingSenderId: '701387500306',
    projectId: 'flutter-chat-app-140f2',
    storageBucket: 'flutter-chat-app-140f2.appspot.com',
    iosBundleId: 'com.chatapp.chatApp.RunnerTests',
  );
}
